# Buildpack API version
api = "0.6"

# Buildpack ID and metadata
[buildpack]
id = "hello-anthony-after"
uri = "."
version = "0.1.0"
name = "Hello from Anthony Buildpack After"
homepage = "https://blog.dahanne.net"

# Stacks that the buildpack will work with
#[[stacks]]
#id = "io.buildpacks.samples.stacks.bionic"
#
#[[stacks]]
#id = "io.buildpacks.samples.stacks.alpine"
#
[[stacks]]
id = "net.dahanne.anthony"
